spring:
  main:
    allow-bean-definition-overriding: true

  datasource:
    url: jdbc:mysql://localhost:3306/3ddang?serverTimezone=Asia/Seoul
    username: root
    password: TmflEkd7!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 5000
    open-in-view: false

  flyway:
    enabled: false

open:
  api:
    region:
      service: service
      key: key

data:
  init:
    region:
      enabled: false
    auction:
      enabled: false
    user:
      enabled: false

image:
  store:
    dir: /Users/jamie/test-3ddang/

token:
  jwt:
    access-key: thisistoolargeaccesstokenkeyfordummykeydataforlocal
    refresh-key: thisistoolargerefreshtokenkeyfordummykeydataforlocal
    access-expired-hours: 12
    refresh-expired-hours: 1460

oauth2:
  client:
    providers:
      kakao:
        user-info-uri: https://kapi.kakao.com/v2/user/me
        user-unlink-uri: https://kapi.kakao.com/v1/user/unlink

fcm:
  enabled: false
  key:
    path: classpath:firebase/private-key.json
